load("@rules_cc//cc:defs.bzl", "cc_binary", "cc_library", "cc_test")

cc_test(
    name = "beer_test",
    srcs = ["beer_test.cc"],
    deps = [
        "@com_google_googletest//:gtest_main",
    ],
)

cc_test(
    name = "tshoot",
    srcs = ["tshoot_test.cc"],
    deps = [
        "@com_google_googletest//:gtest_main",
    ]
)